### ISSUE TITLE
Moving external Google fonts into repo fails

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3026]
Move google fonts into this repo and serve locally and include in distribution builds. The following has been attempted however chrome is currently not attempting to download the fonts locally (no errors are thrown either).

### Download fonts / add to repo

https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc4.woff2
https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2
https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc4.woff2

Into a `src/content/fonts` folder.

### Loading the .woff2 files w/ file-loader

Add a module rule to `webpack.common.js` to handle `.woff2` files, such as:

```js
{
  test: /\.(woff|woff2|ttf|eot)$/,
  use: [{
    loader: 'file-loader',
    options: {
      name: '[name].[ext]',
      // Relative paths and absolute paths have been tried as well:
      // useRelativePath: true, 
      // publicPath: 'http://localhost:6001/fonts/'
    }
  }],
}
```

### Remove legacy font loading
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.4.0/src/app/bootstrap.js#L40

### Add font-face to src/content/styles/main.scss

```css
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 500;
    src: local('Roboto Medium'),
        local('Roboto-Medium') url('../fonts/KFOlCnqEu92Fr1MmEU9fBBc4.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC,
        U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 400;
    src: local('Roboto'),
        local('Roboto-Regular') url('../fonts/KFOmCnqEu92Fr1Mu4mxK.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC,
        U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 700;
    src: local('Roboto Bold'),
        local('Roboto-Bold') url('../fonts/KFOlCnqEu92Fr1MmWUlfBBc4.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC,
        U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

### Notice font files not being loaded in dev tools

`npm run build` should show the font files in `build/fonts/*.woff2` and at the bottom of `build/rv-styles.css` the font-face definitions correctly link to the fonts folder.

There is no attempt by chrome to load the font files when testing with `npm run serve`.
